### ISSUE TITLE
TypeError: node.getAttribute is not a function at new create

### ISSUE THREAD

**Issue by brandondurham** [svgdotjs/svg.js#775] opened 2018-01-04 22:08 UTC
I know this has been brought up before, but I don’t see my particular issue anywhere.

When loading an external SVG as a string and then adding it to the SVG I get this error:

```
svg.js?a2bf:1037 Uncaught (in promise) TypeError: node.getAttribute is not a function
    at new create (svg.js?a2bf:1037)
    at Function.SVG.adopt (svg.js?a2bf:135)
    at initializer.get (svg.js?a2bf:3174)
    at eval (VM157570 1650:436)
    at <anonymous>
```

Here is the code where I do this:

```
// … earlier in the code

// Create the main SVG wrapper
this.main = this.svg.group()
	.addClass(this.options.className)
	.attr('id', this.options.svgID);


/**
 * Load a single tile or series of tiles
 * @method  loadTiles
 * @param   {Number}  index  The index of the tile to start with
 * @param   {Function}  callback  Callback function
 * @return  {Void}
 */
loadTiles(index, callback) {
	const {
		family,
		isLoadingImages,
		tileClass,
		tiles
	} = this.options;

	const totalImages = tiles.length - 1;

	// Make this a local function so we can call it until all
	// tiles have been loaded
	const loadTile = (pointer) => {
		const tileData = tiles[pointer];

		loadRawSVG(tileData.gallery_tile_svg.image)
		.then((response) => {
			// Add the tile SVG
			this.main.svg(response);

			// Grab a reference to the tile we just added
			const theTile = this.main.get(pointer);

			// Set the tiles up for display
			theTile // standard tile
				.data('home', position)
				.data('index', pointer)
				.attr('id', `${family}_${pointer}`)
				.addClass(tileClass);

			// If we haven't reached the final tile, bump the pointer and load the next
			if (pointer < totalImages && isLoadingImages) {
				loadTile(pointer + 1);
			} else if (callback && typeof callback === 'function' && pointer !== 0) {
				callback();
			}
		});
	};

	loadTile(index);
}
```

It’s here that the script fails:

```
const theTile = this.main.get(pointer);
```

Any suggestions around what might be happening?

**Comment by brandondurham** [comment] 2018-01-04 22:27
This only happens when I load more than one SVG, too. The first loads perfectly fine.

**Comment by Fuzzyma** [comment] 2018-01-04 22:28
Please try to pin down your problem to a reproducable example. It's hard to debug that as it is

**Comment by brandondurham** [comment] 2018-01-04 22:36
Sure thing. Coming up.

**Comment by brandondurham** [comment] 2018-01-04 23:17
Put this together quickly: https://jsfiddle.net/brandondurham/6agxjg4t/4/

**Comment by Fuzzyma** [comment] 2018-01-05 00:16
With reproducable example I mean **minimal code**. I dont want to search through that much code

**Comment by brandondurham** [comment] 2018-01-05 01:13
Sure thing. This is about as minimal as it can get: https://jsfiddle.net/brandondurham/6agxjg4t/5/

It’s line 89 where the error occurs, and only with the second SVG that’s loaded.

Really appreciate the help.

**Comment by Fuzzyma** [comment] 2018-01-05 01:55
I dont get any error

**Comment by brandondurham** [comment] 2018-01-05 01:56
I’m getting the following every time:

![image](https://user-images.githubusercontent.com/250210/34592413-c3f259ba-f191-11e7-81ab-dfafddc8adbc.png)

**Comment by Fuzzyma** [comment] 2018-01-05 02:04
Neither with FF nor with Chrome any error

**Comment by brandondurham** [comment] 2018-01-05 02:06
No idea what to say. I get the error every time and have spent hours trying to track it down. As soon as it’s thrown the app breaks.

**Comment by Fuzzyma** [comment] 2018-01-05 02:13
Me neither. I open the fiddle, open the console and click Run. I get a warning that the babel in browser translation is used but thats all

**Comment by saivan** [comment] 2018-01-05 14:31
I get it too:

![image](https://user-images.githubusercontent.com/8543370/34613281-50f96890-f281-11e7-8097-2dd7a00462c5.png)

**Comment by saivan** [comment] 2018-01-05 14:38
My first thought is that it might be a typescript problem, as a start, try with the unminified version and try to figure out if and where the problem occurs.

**Comment by brandondurham** [comment] 2018-01-05 15:03
Great idea. Thanks.

**Comment by brandondurham** [comment] 2018-01-06 22:34
It fails here:

```
this._stroke = node.getAttribute('stroke') || this._stroke
```

**Comment by brandondurham** [comment] 2018-01-06 22:42
In fact, anywhere is uses `getAttribute` it fails. Something going on with my SVG that I just can’t nail.

**Comment by brandondurham** [comment] 2018-01-06 23:22
(Sorry for the rapid posts.) In logging `node`…

```
console.log('NODE', node);
this._stroke = node.getAttribute('stroke') || this._stroke
```

It fails at a `#text` node.

![image](https://user-images.githubusercontent.com/250210/34644918-8eb67e24-f30e-11e7-9a21-0d8848753dc6.png)

**Comment by saivan** [comment] 2018-01-07 03:13
Could you post another example with the unminified code so I can take a look.

**Comment by Sohail012** [comment] 2018-03-28 09:32
rails-ujs.self-817d9a8cb641f7125060cb18fefada3f35339170767c4e003105f92d4c204e39.js?body=1:471 Uncaught (in promise) TypeError: link.getAttribute is not a function
    at Object.Rails.handleMethod (rails-ujs.self-817d9a8cb641f7125060cb18fefada3f35339170767c4e003105f92d4c204e39.js?body=1:471)
    at afterConfirmCallback (rails-sweetalert2-confirm.self-1cadfeb9c06d85cbba43490f4e868b0d7c4de57984f85168452345e4eedd55a9.js?body=1:131)

**Comment by Fuzzyma** [comment] 2018-05-26 19:28
I still cannot reproduce this problem because your fiddle dies when trying to run babel.
I will close this because of no feedback, Feel free to report back when you have new information (or a working fiddle^^)

**Closed by Fuzzyma** 2018-05-26 19:28 UTC
