### ISSUE TITLE
Error: Unbound namespace prefix: "svgjs"

### ISSUE THREAD

**Issue by BuyingANew-Soul** [svgdotjs/svg.js#1296] opened 2023-04-10 04:09 UTC
In the text nodes svgjs:data attribute is causing the error. I am using svgjs in nodejs environment. 
```
<text transform="matrix(0.7257 -0.2285 0.3004 0.9538 5258.6953 5362.7295)" x="7844.0200723945545" y="1879.1765428204626" svgjs:data="{&quot;leading&quot;:&quot;1.3&quot;}">
                    <tspan x="0" y="0" fill="#E74810" font-family="'ArialMT'" font-size="5px">Code:BR 4001, Size:X
                    </tspan>
                    <tspan x="50.029" y="0" fill="#E74810" font-family="'ArialMT'" font-size="5px">L</tspan>
 </text>
```

**Comment by Fuzzyma** [comment] 2023-04-10 17:55
I need more context. Whats your code?

**Comment by Fuzzyma** [comment] 2023-04-11 18:36
You can just change the id after clone. That would make things easier 🤔

**Comment by BuyingANew-Soul** [comment] 2023-04-12 08:30
I thought about this but didn't try because these elements contain several childNodes with different ids and nested nodes. I thought taking the strings would be easier that time until I faced this error. 
I am going to try the solution you proposed. Do you suspect anything that's wrong with the current approach?

**Comment by Fuzzyma** [comment] 2023-04-12 10:12
I guess you are using svgdom? Seems like its parser is not happy about the svgjs namespace. didnt encounter that error before tho. You can try to remove the namespace on export by passing a function into the `svg()` function. That function will be called on every node. If you remove the svgjs:data attribute, the import should work.

**Comment by BuyingANew-Soul** [comment] 2023-04-13 17:28
I implemented the a new version with the cloning. The error is gone, and I am able successfully write the new svg file. But for those elements I was facing the error now in the output svg they are not showing! Also the moving of the parts are not correct. 
Please checkout this simple version:
```
const fs = require('fs');
const { createSVGWindow } = require('svgdom')
const window = createSVGWindow()
const document = window.document
const { SVG, registerWindow } = require('@svgdotjs/svg.js')
//const {svgFromFile, readAllSvgs, writeSvg} = require('./readingSvg');

// register window and document
registerWindow(window, document);

const svgFromFile = (path) => {
    try {
        const svgString = fs.readFileSync(path, 'utf8');
        return svgString;
    } catch (err) {
        console.error(err);
    }
    
};


const svgFromString = (string) => {
    
    const draw = SVG(document.documentElement);
    var svg = draw.svg(string);
    return svg;
        
};


const writeSvg = (svg, name) => {
   
    fs.writeFile(name, svg, err => {
    if (err) {
        console.error(err);
    }
    // file written successfully
    });
};



var svgString = svgFromFile("svgs/test svgs/bib1.svg");
var svg = svgFromString(svgString);
//console.log(svg.svg())

// getting the specific element
let selector = `[id*="P8_5_"]`;
const element = svg.findOne(selector);

var el = element.clone()
el.move(100,100);

svg.clear()
svg.width(4000);
svg.height(4000);
svg.viewbox(0,0,4000,4000);
svg.add(el);

writeSvg(svg.svg(), 'svgs/new.svg');


```
The input svg is:
https://github.com/BuyingANew-Soul/prepare-nest-file/blob/master/svgs/test%20svgs/bib1.svg?short_path=370b066
If I choose any of the Element whose id starts with P (P8_5_, P7_5_ etc), then the output is like this:
https://github.com/BuyingANew-Soul/prepare-nest-file/blob/master/svgs/new.svg?short_path=380691d
But for other elements like Right_thigh_3_, Left_thigh_3_ etc, the same code works fine. 
Am  I doing something wrong here?

**Comment by Fuzzyma** [comment] 2023-09-02 19:40
Sorry for the late reply. Your svgs are fairly big. Its hard to see what the issue is. 

Can you create a minimal example that showcases the bug?

**Comment by Fuzzyma** [comment] 2023-09-03 12:48
should be fixed in master

**Closed by Fuzzyma** 2023-09-03 12:48 UTC
