### ISSUE TITLE
SVG.prepare does not get called using Next.js 7

### ISSUE THREAD

**Issue by justsee** [svgdotjs/svg.js#907] opened 2018-09-20 06:10 UTC
# Bug report

`svg.js`'s `move` function errors in Next.js 7 after [this commit](https://github.com/zeit/next.js/commit/75476a91362d6dc4e9fe7bda103adeab1e81f2d8) (which adds Webpack 4).

The error logged is: `TypeError: SVG.parser.path is undefined, can't access property "setAttribute" of it`.

It appears [SVG.prepare()](https://github.com/svgdotjs/svg.js/blob/97da895ef24168a9d483f7701b58460d81b96cf2/src/svg.js#L153-L156) is not getting called.

Manually calling this before using the library works as expected.

**Comment by Fuzzyma** [comment] 2018-11-08 14:41
@justsee can you try the 3.0 branch? It should work as expected there. And as a bonus you have es6 modules and can use webpack to bundle only what you need ;)

**Comment by saivan** [comment] 2019-03-22 01:08
I'm going to close this, if you have any more questions; let us know :)

**Closed by saivan** 2019-03-22 01:08 UTC

**Comment by razvanioan** [comment] 2021-02-05 17:53
@justsee Thx for the fix!

I confirm that this happening for SVG 2.7.1 if used in a dynamic loaded module of a Vue.js v2.5 app

It is working fine if the module is embedded into the app (and not loaded async), so it must be a problem if the library is loaded async

**Comment by Fuzzyma** [comment] 2021-02-05 20:34
Version 2 of svg.js is long outdated. Try v3. Also, you can just call `SVG-prepare()` yourself

**Comment by razvanioan** [comment] 2021-02-06 03:13
Yeah, I gave a try to v3 but I couldn't make it work with select & resize under Vue components, I guess something about loading & instantiating SVG was the cause as resize couldn't see SVG

I'll give another try later on
