### ISSUE TITLE
Animate flip / transform / matrix problems

### ISSUE THREAD

**Issue by Spica2** [svgdotjs/svg.js#784] opened 2018-01-19 12:24 UTC
I had some troubles to reverse flip animations. So if I do
```
    item.animate().flip(x)
    item.animate().transform(new SVG.Matrix({ a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 }))
```

I get floating values like
```
    matrix(0.9999999999999998,0,0,1,2.2737367544323206e-13,0)
```
This makes further operations difficult

For now I came up with
```
    item.animate().flip(x).after(function(situation) {
				item.flip('x')
			})
```
which results e.g. in
```
    matrix(-1,0,0,1,452,0)
```
A more convenient way would be nice

**Comment by Fuzzyma** [comment] 2018-01-19 12:27
> This makes further operations difficult
 
Why is that so? These values are rounding mistakes which are quite common on the floating point world.
However they dont stopy you from using them as a normal number. `0.9999999999999998` is literally `1`. If you need to compare these values somehow, just use a small enough epsilon for comparison

**Comment by Spica2** [comment] 2018-01-19 12:47
Yes, thought that, too. But I do get this error very often
```Error: <use> attribute transform: Expected number, "matrix(1,0,0,1,5.60519385729926…".```
With rounded numbers it s all ok.

**Comment by saivan** [comment] 2018-02-08 15:24
Can you post a reproducible example of your error?
I can't reproduce it. Perhaps in a jspen or something?

**Comment by Fuzzyma** [comment] 2018-02-08 21:05
Will close this until we get feedback

**Closed by Fuzzyma** 2018-02-08 21:05 UTC
