### ISSUE TITLE
Test fails randomly in the FX module

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.js#539] opened 2016-10-20 16:25 UTC
We got a test in [spec/fx.js line 81](https://github.com/wout/svg.js/blob/master/spec/spec/fx.js#L81) that [sometimes fails](https://travis-ci.org/wout/svg.js/builds/168788993#L1023).
Its written by @wout on 2016-08-04 b0a8b25f.

Since @RmiTtro just did a rewrite of some of the functionality in that module, perhaps he can take a look?

The issue seems to be than the test expects `fx.situation.duration` to be greater than it actually is. E.i. it has do to with timing which is exactly what #536 changed. Seems reasonable to assume its connected.

Would be really nice to not have a red failing build badge.

**Comment by Fuzzyma** [comment] 2016-10-20 16:29
not written by him but last changed by him^^
Its actually mine. The problem is timing. Actually the condition there should be always true but duo to same time travelling stuff (haha) time does not pass (or JS ist just to fast)

**Comment by dotnetCarpenter** [comment] 2016-10-20 16:34
Remember that javascript is **sequential**. There has to be a `setTimout` or some asynchronous function call before **time** pass.

**Comment by Fuzzyma** [comment] 2016-10-20 16:37
i know that^^. Its a test of teh animation module. ZTime actually pass there^^

**Comment by dotnetCarpenter** [comment] 2016-10-20 16:39
Sorry, didn't mean to be condescending. Was hoping this would be a simple issue.

**Comment by RmiTtro** [comment] 2016-10-20 16:46
Hehe, I think I already have a solution for this one ;)! In my pull request, In my pull request #538 I changed this test to make it simpler. There is still some work to be done on my pull request but once it is merged it should fix this issue.

**Comment by Fuzzyma** [comment] 2016-10-20 16:47
oh - cool

**Comment by wout** [comment] 2016-10-20 18:01
Strangest thing is I can't recall making changes there recently...

**Comment by Fuzzyma** [comment] 2016-10-20 18:14
I guess you tried to correct all the decimal errors in one rush

**Comment by RmiTtro** [comment] 2016-11-04 07:22
Since pull request #538 has been merged, I think we can mark this issue as solved. In this pull request, I modified all tests using setTimeout to use the Jasmine clock module instead. So this issue shouldn't happen again (as an added bonus, it now takes less than 1 second to run all the tests).

**Closed** 2016-11-04 11:05 UTC
