### ISSUE TITLE
error TS2416: Property 'at' in type 'PointArray' is not assignable to the same property in base type 'Array<ArrayXY>'.

### ISSUE THREAD

**Issue by lukatendai** [svgdotjs/svg.js#1212] opened 2021-08-14 15:09 UTC
Error: node_modules/@svgdotjs/svg.js/svg.js.d.ts:380:9 - error TS2416: Property 'at' in type 'PointArray' is not assignable to the same property in base type 'Array<ArrayXY>'.
  Type '(pos: number) => PointArray' is not assignable to type '(index: number) => ArrayXY'.
    Type 'PointArray' is not assignable to type 'ArrayXY'.

380         at(pos: number): PointArray;
            ~~

Error: node_modules/@svgdotjs/svg.js/svg.js.d.ts:439:9 - error TS2416: Property 'at' in type 'PathArray' is not assignable to the same property in base type 'Array<PathCommand>'.
  Type '(pos: number) => PathArray' is not assignable to type '(index: number) => PathCommand'.
    Type 'PathArray' is not assignable to type 'PathCommand'.
      Type 'PathArray' is not assignable to type '["a" | "A", number, number, number, number, number, number, number]'.

It looks like at should return element of the array not the whole array?

**Comment by Fuzzyma** [comment] 2021-08-15 11:12
No it does return the whole array but as far as I know this Funktion is not used anymore? Have to double check

**Comment by crystalfp** [comment] 2021-08-16 10:52
As a test I commented the two lines in svg.js.d.ts (380 and 439) and now the application compiles and runs without errors.

**Comment by larshp** [comment] 2021-08-17 08:27
hmm, same issue here, commented the lines, but its just a temporary fix

**Comment by Basementbrb** [comment] 2021-09-04 18:24
@Fuzzyma looks like you removed the function from `PointArray` and `PathArray` in this commit: https://github.com/svgdotjs/svg.js/commit/747f8e810eea3bb4836b50f411a7de6f5d67cbfa#

**Comment by Fuzzyma** [comment] 2021-09-06 10:45
@Basementbrb in that case it should be removed form the typescript file alltogether

**Comment by meriturva** [comment] 2021-11-15 16:00
Just to know, any ETA when the new version will be released?

**Comment by MuhKuh7** [comment] 2021-12-20 12:05
any update?

**Comment by larshp** [comment] 2022-01-27 06:02
new version released, see https://github.com/svgdotjs/svg.js/issues/1245#issuecomment-1022660309

I can confirm that the new release solves my issue ❤️

**Closed** 2022-01-27 08:31 UTC
